# Generated by Django 2.1.5 on 2019-01-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='영단어를 입력하세요. (최대 20자)', max_length=20, verbose_name='단어')),
                ('mean', models.TextField(help_text='영단어의 뜻을 입력하세요.', verbose_name='단어의 뜻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
